### ISSUE TITLE
Optionally hide outdated repositories from badges

### ISSUE THREAD

**Issue by dreua** [repology/repology-webapp#117]
I would like to have an option to show only maintained repositories in a badge or a version matrix. I know I can hand pick repositories using `repos=` but compiling and maintaining the list of active repositories in different places of documentation for different projects is not really efficient.

Take the following matrix as an example. I haven't checked all the repositories but at least Fedora 26-29 and Ubuntu 12.04, 14.04 and 19.04 are EOL and there is nothing I can do about outdated versions in those as a project or packet maintainer.

![pdfarranger version matrix](https://repology.org/badge/versions-matrix.svg?projects=pdfarranger,python:pikepdf%3E=1.7,pdfshuffler&header=pdfarranger%20packaging%20status)

**Comment by AMDmi3** [comment]
> I would like to have an option to show only maintained repositories in a badge or a version matrix. I know I can hand pick repositories using repos= but compiling and maintaining the list of active repositories in different places of documentation for different projects is not really efficient.

To have such an option, the same list of active repositories would have to be maintained in Repology, which I do not plan to do. I see no objective criteria to do it automatically, and I do not see reason to, because with filtered repositories there's no telling whether repository is not supported by Repology or does not suit the filtering criteria. Also, mentioned EoLed repositories are still somewhat widely used, and it makes sense to inform users that these are explicitly not supported.

**Comment by keszybz** [comment]
Hmm, I wanted to open the same issue and found this…

I care in particular about Fedora: it releases twice per year, and the EOL accumulate pretty quickly. And anything below F33 is dead weight: as soon as the release goes EOL, any updates are blocked. So at end of 2022 this badge will show 10 dead Fedora versions and at most 4 live ones.

It is somewhat useful to *users* to see the EOL versions, but pretty much useless to maintainers. I think it'd make a lot of sense to have a filter for EOL releases, that would be maintained as "best effort": when somebody adds a new release they could check if the previous one has gone stale, or just mark it as such when they notice.

**Comment by AMDmi3** [comment]
Ok, let's do this then.
