### ISSUE TITLE
Update to Bootstrap 5 from v3.3.7

### ISSUE THREAD

**Issue by ghost** [repology/repology-webapp#161]

**Comment by AMDmi3** [comment]
Yes, this is in fact long desired, mostly for support for grids which would allow to improve projects filter form, but a lot of other features can be taken advantage of.

**Comment by AMDmi3** [comment]
We will not switch to a newer bootstrap.  After a couple of attempts it looks like it's a massive regression as no longer provides appropriate margins by default and require setting corresponding classes in HTML by hand. This is clumsy, inflexible, and hinders separation of layout and styling. In fact, bootstrap is crippled by design by being not BEM compatible.

Custom CSS needs to be written from scratch - it's a huge work, but it's necessary for proper support of growing number of repology frontend features.
