### ISSUE TITLE
CVE: Wrong range shown

### ISSUE THREAD

**Issue by susnux** [repology/repology-webapp#164]
Example package zabbix: https://repology.org/project/zabbix/cves

If you filter version `4.0.28` it shows CVE-2019-17382 and CVE-2019-15132.
zabbix 4.0.x and 4.2.x are different branches, that means 4.0.x might not be affected even when it shown "up to 4.2.5".

CVE-2019-15132 for example is fixed in 4.0.24

A solution might be to parse affected configurations: https://nvd.nist.gov/vuln/detail/CVE-2019-15132/cpes?expandCpeRanges=true

**Comment by AMDmi3** [comment]
Please submit correction to NVD to fix this - if the vulnerability was fixed in multiple branches, there should be multiple ranges for CPE in NVD, like, for example, for https://nvd.nist.gov/vuln/detail/CVE-2016-10742. There's no ambiguous parsing here, a single range "up to X" means "up to X" without exceptions.
