### ISSUE TITLE
Feature request: At query projects, allow to exclude the presence of ignored versions

### ISSUE THREAD

**Issue by superherointj** [repology/repology-webapp#192]
Use case:

Tried to filter projects missing from nixpkgs which exist in other repositories. Problem is, as nixpkgs doesn't include letters at beginning of version names, the amount of false positives is huge.

Root issue seems to be the ~~awful~~ (Update: sorry about the poor choice of word here) matching of versions between nixpkgs and repology. But...

A workaround could be used to filter out any project that has any ignored version. Making possible to list missing projects from nixpkgs that exist on other repositories without too much noise.

Sample query:
![image](https://user-images.githubusercontent.com/5861043/164253526-5d304f16-05a6-4e85-9362-038982384825.png)

Sample project (named: lshw) that exist on nixpkgs and still shows up:
![image](https://user-images.githubusercontent.com/5861043/164253628-4154617d-2f90-4aa2-893f-2fa97364e39e.png)

There should be a way to exclude any package having ignored versions from showing up on results.

If there is a better solution to this, let me know. I'm just trying to find a solution.

**Comment by AMDmi3** [comment]
> Tried to filter projects missing from nixpkgs which exist in other repositories

For the record, version matching problems should not affect this task is any way. There are plenty name mismatches too, though.

> Root issue seems to be the awful matching of versions between nixpkgs and repology

If there are cases where the problem is on repology side, I'd like to see some examples.

> Sample project (named: lshw) that exist on nixpkgs and still shows up:

It has nothing to do with ignored versions. For repology this project does not exist is nix unstable, because it is not parsed from the data dump, because the version is not defined there:
```
    "lshw": {
      "name": "lshw-B.02.18",
      "pname": "lshw-B.02.18",
      "version": "",
```
this is a known problem where nix cannot reliably split `name` to an actual package name and a version according to its own rules, however there was some effort to allow to specify `pname` and `version` separately. According to https://github.com/NixOS/nixpkgs/commit/8d0267dc8f02e010785d6f90573ea1135b7957e7 this is already in place, but some bits required to propagate this to a dump are still missing, so we are left with concatenated `name` again.

**Comment by superherointj** [comment]
You are right. Sorry about my ignorance. I totally misunderstood the root issue.

Nix is outputting versions in a wrong (for our purposes) manner.

And a possible solution is not agreed upon yet:
https://github.com/NixOS/nix/pull/4463

Still the proposed workaround could still make sense. But I understand this should be solved on the Nix side.

Thanks for answering.

**Comment by AMDmi3** [comment]
Meanwhile, I've added logging of empty version problems to [https://repology.org/repositories/updates](parsing logs).
