### ISSUE TITLE
Badge must be searchable

### ISSUE THREAD

**Issue by vitaly-zdanevich** [repology/repology-webapp#220]
![image](https://user-images.githubusercontent.com/3514015/225743232-896dd02d-81a2-4dfa-8f36-631cbdd72a49.png)

Now <kbd>Ctrl-F</kbd> will not give any result :(

And maybe clickable in every cell?

We can use SVG for that.

**Comment by AMDmi3** [comment]
The image above is png because that's how GitHub embeds it.
If you open svg directly, you can search it, buy even if you embed it as svg browers won't generally allow you to search in it and interpret links in it. Also, where would you expect these links to point to? Repology does not have per-package pages.

**Comment by vitaly-zdanevich** [comment]
> if you embed it as svg browers won't generally allow you to search in it

SVG [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text) is searchable by `cat`

**Comment by AMDmi3** [comment]
Because it's iframe
